apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: frontend, namespace: cairops-lab}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: frontend}
  minReplicas: 2
  maxReplicas: 6
  behavior:
    scaleUp: {stabilizationWindowSeconds: 0}
    scaleDown: {stabilizationWindowSeconds: 60}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: {type: Utilization, averageUtilization: 60}
